name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: short
  RUSTDOCFLAGS: "-F broken-intra-doc-links"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: cargo +nightly fmt -- --check

    - name: Build
      run: cargo +nightly build --verbose --features nightly

    - name: Document
      run: cargo +nightly doc --document-private-items

    - name: Run tests
      run: cargo +nightly test --verbose --features nightly
